import Head from "next/head";
import Link from "next/link";

import styles from "@/styles/Profile.module.scss";

// import { cat } from "../../models/cat.interface";
import { Inter } from "next/font/google";

import { GetCat } from "@/services/cat.service";

import { wrapper } from "@/store/index";
import { addCat } from "@/store/cat/action";
import { useEffect } from "react";
import useAxiosAuth from "@/common/hook/useAxiosAuth";
import { addUser } from "@/store/user/action";
import { useDispatch, useSelector } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

interface ProfileProps {
  // posts: cat[];
}

export default function Profile({ ...ProfileProps }: ProfileProps) {
  const axiosAuth = useAxiosAuth();
  const dispatch = useDispatch();
  const fetch = async () => {
    let response = await axiosAuth.get("http://localhost:4000/api/user/me");
    dispatch(addUser(response.data));
  };
  useEffect(() => {
    fetch();
  }, []);

  const user = useSelector((state: any) => state.user.user);
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.info}>
          <p>Account: {user.username}</p>
          <p>Role: {user.role}</p>
        </section>
      </main>
      <Link href={`/admin`} className={styles.detailBottom}>
        <button>Quay lại</button>
      </Link>
    </>
  );
}
