import Head from "next/head";

import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["vietnamese"] });

interface ProtectedProps {}

export default function Protected({ ...ProtectedProps }: ProtectedProps) {
  return (
    <>
      <Head>
        <title>404</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>hi</main>
    </>
  );
}
