import Head from "next/head";

import styles from "@/styles/Login.module.scss";

import { FormEvent, FormEventHandler, useState } from "react";
import { Inter } from "next/font/google";

import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { signIn } from "next-auth/react";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["vietnamese"] });

interface LogProps {
  posts: "";
}

export default function Log({ ...HomeProps }: LogProps) {
  const [input, setInput] = useState({ username: "", password: "" });
  const { push } = useRouter();

  const change_input = (e: any, name: string) => {
    setInput({
      ...input,
      [name]: e.target.value,
    });
  };

  const submit: FormEventHandler<HTMLFormElement> = async (
    event: FormEvent
  ) => {
    event.preventDefault();
    const result: any = await signIn("credentials", {
      username: input.username,
      password: input.password,
      redirect: false,
    });

    if (result && result.ok) {
      toast.success("Login successfully");
      push("/admin");
    }
    if (result && !result.ok) {
      toast.error("Login failed");
    }
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.card}>
          <form onSubmit={submit} className={styles.cardChild}>
            <h3>Đăng nhập</h3>
            <div>
              <label>Tài khoản</label>
              <input
                placeholder="Nhập tài khoản ..."
                type="text"
                value={input.username}
                onChange={(e) => {
                  change_input(e, "username");
                }}
              />
            </div>
            <div>
              <label>Mật khẩu</label>
              <input
                placeholder="Nhập mật khẩu ..."
                type="password"
                value={input.password}
                onChange={(e) => {
                  change_input(e, "password");
                }}
              />
            </div>
            <button>Đăng nhập</button>
          </form>
        </section>
      </main>
    </>
  );
}
